# Generated by scripts/brew-formula.sh in aryanmehrotra/sbx. Do not edit by hand:
# the checksums come from the release's own SHA256SUMS.
class Sbx < Formula
  desc "Per-branch sandboxes that sleep when nobody is using them"
  homepage "https://github.com/aryanmehrotra/sbx"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.2.0/sbx_v0.2.0_darwin_arm64"
      sha256 "99606894fdeeb443b117c6883f33aaf520a57cfb5bfe4e3e9777f85b596fbe16"
    end

    on_intel do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.2.0/sbx_v0.2.0_darwin_amd64"
      sha256 "172c0f97ce36a3b5482498eaaa161289764eb6c3e0eb41da08f81ee77e1e5b01"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.2.0/sbx_v0.2.0_linux_arm64"
      sha256 "575a6a5b134cd255e03e5c3f674c8ba7b9f27b334d25a25c2e56006b01bbdf0c"
    end

    on_intel do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.2.0/sbx_v0.2.0_linux_amd64"
      sha256 "8ec42cd11e74736b58a76c577663d225fb091bb9123d58f6a850c20ca3bd0ffd"
    end
  end

  def install
    # The download is a bare binary, not an archive, so it arrives without an exec bit and
    # under its platform-specific name.
    binary = Dir["sbx_*"].first
    chmod 0755, binary
    bin.install binary => "sbx"
  end

  def caveats
    <<~EOS
      sbx needs its daemon running to hand out addresses:

        sbx serve --idle 5m &

      deploy/ in the repository has a launchd plist and a systemd unit, both running as you
      rather than as root. Check what this host can do with:

        sbx doctor
    EOS
  end

  test do
    # Two things worth failing on: the binary runs at all on this platform, and it is the
    # version the formula claims. A formula that installs the wrong release still passes a
    # test that only greps the help text.
    assert_match "v#{version}", shell_output("#{bin}/sbx --version")

    # 2>&1 because v0.1.0 printed --help to stderr. Fixed after that release, and merging the
    # streams here keeps this formula working against both.
    assert_match "sandboxes", shell_output("#{bin}/sbx --help 2>&1")
  end
end
