# Generated by scripts/brew-formula.sh in aryanmehrotra/sbx. Do not edit by hand:
# the checksums come from the release's own SHA256SUMS.
class Sbx < Formula
  desc "Per-branch sandboxes that sleep when nobody is using them"
  homepage "https://github.com/aryanmehrotra/sbx"
  version "0.13.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.13.2/sbx_v0.13.2_darwin_arm64"
      sha256 "b643d90962843a5cbd8064813724469facec9e874983963a02a481938f4fd2b1"
    end

    on_intel do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.13.2/sbx_v0.13.2_darwin_amd64"
      sha256 "282710385ad415728df44cd44885dc989f787cee43587aafa5d073c683890b90"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.13.2/sbx_v0.13.2_linux_arm64"
      sha256 "f7cf8c852dcf220118e9502bd1dad89608ea90ee45111bdc3e38bc9033977ee7"
    end

    on_intel do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.13.2/sbx_v0.13.2_linux_amd64"
      sha256 "776872fb913558bb0c26b93b6c36930f44f6d2f49df77bfecbc88f341a4548f1"
    end
  end

  def install
    # The download is a bare binary, not an archive, so it arrives without an exec bit and
    # under its platform-specific name.
    binary = Dir["sbx_*"].first
    chmod 0755, binary
    bin.install binary => "sbx"
  end

  def caveats
    <<~EOS
      sbx needs its daemon running to hand out addresses:

        sbx serve --idle 5m &

      deploy/ in the repository has a launchd plist and a systemd unit, both running as you
      rather than as root. Check what this host can do with:

        sbx doctor
    EOS
  end

  test do
    # Two things worth failing on: the binary runs at all on this platform, and it is the
    # version the formula claims. A formula that installs the wrong release still passes a
    # test that only greps the help text.
    assert_match "v#{version}", shell_output("#{bin}/sbx --version")

    # 2>&1 because v0.1.0 printed --help to stderr. Fixed after that release, and merging the
    # streams here keeps this formula working against both.
    assert_match "sandboxes", shell_output("#{bin}/sbx --help 2>&1")
  end
end
