# Generated by scripts/brew-formula.sh in aryanmehrotra/sbx. Do not edit by hand:
# the checksums come from the release's own SHA256SUMS.
class Sbx < Formula
  desc "Per-branch sandboxes that sleep when nobody is using them"
  homepage "https://github.com/aryanmehrotra/sbx"
  version "0.15.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.15.0/sbx_v0.15.0_darwin_arm64"
      sha256 "eaf3bfc9e5df95323dee672cab5a65ac86dbc6949cdcd455a5f6abe8e7b4b3a5"
    end

    on_intel do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.15.0/sbx_v0.15.0_darwin_amd64"
      sha256 "02e2b304c1a2661734e3ff029a67258976309cfc0652899975670d173df66f85"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.15.0/sbx_v0.15.0_linux_arm64"
      sha256 "b4f891fffd5168f48389b1f660c58a36e1f37533f4fdade74a7e544971374ad5"
    end

    on_intel do
      url "https://github.com/aryanmehrotra/sbx/releases/download/v0.15.0/sbx_v0.15.0_linux_amd64"
      sha256 "09471320adea0e0d7c24e691d0bddbafe7faa3892835cb505fe86ad6cf3ec974"
    end
  end

  def install
    # The download is a bare binary, not an archive, so it arrives without an exec bit and
    # under its platform-specific name.
    binary = Dir["sbx_*"].first
    chmod 0755, binary
    bin.install binary => "sbx"
  end

  def caveats
    <<~EOS
      sbx needs its daemon running to hand out addresses:

        sbx serve --idle 5m &

      deploy/ in the repository has a launchd plist and a systemd unit, both running as you
      rather than as root. Check what this host can do with:

        sbx doctor
    EOS
  end

  test do
    # Two things worth failing on: the binary runs at all on this platform, and it is the
    # version the formula claims. A formula that installs the wrong release still passes a
    # test that only greps the help text.
    assert_match "v#{version}", shell_output("#{bin}/sbx --version")

    # 2>&1 because v0.1.0 printed --help to stderr. Fixed after that release, and merging the
    # streams here keeps this formula working against both.
    assert_match "sandboxes", shell_output("#{bin}/sbx --help 2>&1")
  end
end
